### ISSUE TITLE
Missing Flag for Azerbaijan (country code: AZ)

### ISSUE THREAD

**Issue by stanley-george** [stephenway/react-flagkit#126]
**Describe the bug**
When the following code is used:
```
<Flag country="AZ" />
```
The rendered output is:

![image](https://user-images.githubusercontent.com/7351337/107067556-6ebfd180-67ad-11eb-93cb-e81eb885d3c2.png)

The issue is probably due to the fact that `'AZ'` is missing in the enumeration of country codes here: https://github.com/stephenway/react-flagkit/blob/master/src/countryCodes.ts#L15.

Additionally, I verified that a flag for Azerbaijan is available over the jsDeliver CDN: https://cdn.jsdelivr.net/gh/madebybowtie/FlagKit@2.2/Assets/SVG/AZ.svg

**Desktop:**
 - OS: Mac OS Big Sur
 - Browser Chrome
 - Version 87.0.4280.141 (Official Build) (x86_64)

**Comment by barlima** [comment]
@stephenway any chance to have this solved?

**Comment by stephenway** [comment]
This issue has been resolved. Thanks for the report!

**Comment by gaudiauj** [comment]
Hello @stephenway, is it possible to tag the version ? it's not available yet on npm.
